version: '3.8'

services:
  pokedex-app:
    container_name: pokedex-frontend
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3001:80"

    restart: unless-stopped

    environment:
      - NODE_ENV=production

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M